'use client';

import React, { useEffect, useRef, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { useAppStore } from '@/stores/app-store';
import { useGitData } from '@/context/git-data-provider';
import { useNarrativeGenerator } from '@/hooks/use-narrative-generator';
import { StoryHeader } from '@/components/story/story-header';
import { UnifiedDeveloperJourney } from '@/components/story/unified-developer-journey';
import { PerRepoStoryCards } from '@/components/story/per-repo-story-cards';
import { MilestoneTimeline } from '@/components/story/milestone-timeline';
import { ChapterNavigation } from '@/components/story/chapter-navigation';
import { ShareStory } from '@/components/story/share-story';
import { Progress } from '@/components/ui/progress';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  BookOpen,
  Sparkles,
  Loader2,
  AlertCircle,
  RefreshCw,
  ArrowLeft,
  Zap,
  GitCommit,
  Clock,
  Share2,
} from 'lucide-react';
import type { StoryMilestone } from '@/lib/types';

const PHASE_LABELS: Record<string, string> = {
  idle: 'Ready to generate',
  preprocessing: 'Analyzing commit intelligence',
  'analyzing-repos': 'Deep-diving into repositories',
  correlating: 'Finding cross-repo connections',
  streaming: 'Connecting to Claude',
  'writing-chapters': 'Crafting your narrative',
  enriching: 'Adding finishing touches',
  complete: 'Story complete',
  error: 'Generation failed',
};

const PHASE_ICONS: Record<string, React.ReactNode> = {
  idle: <BookOpen className="h-5 w-5" />,
  preprocessing: <GitCommit className="h-5 w-5 animate-pulse" />,
  'analyzing-repos': <Zap className="h-5 w-5 animate-pulse" />,
  correlating: <Zap className="h-5 w-5 animate-pulse" />,
  'writing-chapters': <Sparkles className="h-5 w-5 animate-pulse" />,
  enriching: <Clock className="h-5 w-5 animate-pulse" />,
  complete: <Sparkles className="h-5 w-5" />,
  error: <AlertCircle className="h-5 w-5" />,
};

export default function StoryPage() {
  const router = useRouter();
  const { selectedRepos } = useAppStore();
  const { selectedRepositories } = useGitData();
  const {
    stories,
    unifiedStory,
    partialStory,
    isGenerating,
    progress,
    narrativeProgress,
    generateStory,
    regenerate,
    error,
  } = useNarrativeGenerator();

  const [activeSection, setActiveSection] = useState<string>('unified-journey');
  const [shareOpen, setShareOpen] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const contentRef = useRef<HTMLDivElement>(null);
  const storyCaptureRef = useRef<HTMLElement>(null);
  const sectionRefs = useRef<Record<string, HTMLElement | null>>({});

  // Route guard: redirect if no repos selected
  useEffect(() => {
    if (selectedRepos.length === 0) {
      router.push('/connect');
    }
  }, [selectedRepos, router]);

  // Auto-generate on first mount if no stories exist
  useEffect(() => {
    if (
      !hasAutoGenerated &&
      !isGenerating &&
      selectedRepos.length > 0 &&
      stories.length === 0 &&
      !unifiedStory &&
      !error
    ) {
      setHasAutoGenerated(true);
      generateStory();
    }
  }, [hasAutoGenerated, isGenerating, selectedRepos, stories, unifiedStory, error, generateStory]);

  // Scroll-spy for chapter navigation
  useEffect(() => {
    const handleScroll = () => {
      const sections = Object.entries(sectionRefs.current);
      let currentSection = 'unified-journey';

      for (const [id, el] of sections) {
        if (el) {
          const rect = el.getBoundingClientRect();
          if (rect.top <= 200) {
            currentSection = id;
          }
        }
      }

      setActiveSection(currentSection);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const registerSection = useCallback((id: string, el: HTMLElement | null) => {
    sectionRefs.current[id] = el;
  }, []);

  const scrollToSection = useCallback((id: string) => {
    const el = sectionRefs.current[id];
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, []);

  // Build a display story from partialStory during streaming, or unifiedStory when complete
  const streamingDisplayStory = React.useMemo(() => {
    if (unifiedStory) return null; // Complete story takes precedence
    if (!partialStory || !partialStory.chapters?.length) return null;

    // Build a minimal GeneratedStory from the partial data
    const chapters = (partialStory.chapters || []).map((ch) => ({
      index: ch.index,
      title: ch.title,
      content: ch.content,
      dateRange: ch.dateRange as { start: string; end: string; totalDays: number },
      repoIds: ch.repoIds,
      anchorId: ch.anchorId,
    }));

    const content = chapters
      .map((ch) => `## ${ch.title}\n\n${ch.content}`)
      .join('\n\n');

    return {
      id: partialStory.id || 'streaming',
      type: 'unified' as const,
      repoId: null,
      title: partialStory.title || 'Your Developer Journey',
      subtitle: partialStory.subtitle || 'Writing your story...',
      content,
      chapters,
      milestones: [],
      generatedAt: Date.now(),
      dateRange: partialStory.dateRange as { start: string; end: string; totalDays: number } || { start: '', end: '', totalDays: 0 },
      model: partialStory.model || '',
    };
  }, [unifiedStory, partialStory]);

  // Gather all chapters and milestones
  const effectiveStory = unifiedStory || streamingDisplayStory;
  const allChapters: Array<{ id: string; title: string; type: 'unified' | 'repo'; repoId?: string }> = [];

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const unifiedStoryAny = (effectiveStory) as any;

  if (unifiedStoryAny) {
    allChapters.push({
      id: 'unified-journey',
      title: 'Developer Journey',
      type: 'unified',
    });
    const chapters = unifiedStoryAny.chapters as Array<{ anchorId: string; title: string }> | undefined;
    if (chapters) {
      chapters.forEach((ch: { anchorId: string; title: string }) => {
        allChapters.push({
          id: ch.anchorId,
          title: ch.title,
          type: 'unified',
        });
      });
    }
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  stories.forEach((story: any) => {
    allChapters.push({
      id: `repo-${story.repoId}`,
      title: story.title as string,
      type: 'repo',
      repoId: (story.repoId as string) || undefined,
    });
  });

  if (stories.length > 0 || unifiedStory) {
    allChapters.push({
      id: 'milestones',
      title: 'Timeline',
      type: 'unified',
    });
  }

  const unifiedMilestones = (unifiedStoryAny?.milestones as StoryMilestone[] | undefined) || [];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const storyMilestones = stories.flatMap((s: any) => (s.milestones as StoryMilestone[]) || []);

  const allMilestones: StoryMilestone[] = [
    ...unifiedMilestones,
    ...storyMilestones,
  ].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

  // Deduplicate milestones by date + title
  const seenMilestones = new Set<string>();
  const uniqueMilestones = allMilestones.filter((m) => {
    const key = `${m.date}-${m.title}`;
    if (seenMilestones.has(key)) return false;
    seenMilestones.add(key);
    return true;
  });

  const isComplete = progress.phase === 'complete';
  const hasContent = stories.length > 0 || unifiedStory !== null || streamingDisplayStory !== null;

  // Generate status for header
  const generationStatus: 'idle' | 'generating' | 'complete' | 'error' =
    isGenerating ? 'generating' : error ? 'error' : isComplete ? 'complete' : 'idle';

  // Calculate date range
  const dateRange = (unifiedStoryAny?.dateRange as { start: string; end: string } | undefined) ||
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (stories.length > 0 ? (stories[0] as any).dateRange as { start: string; end: string } | undefined : undefined);

  if (selectedRepos.length === 0) {
    return null; // Will redirect
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Ambient Background Decoration */}
      <div className="pointer-events-none fixed inset-0 overflow-hidden">
        <div className="absolute -left-40 -top-40 h-80 w-80 rounded-full bg-purple-500/5 blur-3xl" />
        <div className="absolute -right-40 top-1/3 h-96 w-96 rounded-full bg-blue-500/5 blur-3xl" />
        <div className="absolute -left-20 bottom-1/4 h-64 w-64 rounded-full bg-emerald-500/5 blur-3xl" />
      </div>

      <div className="relative">
        {/* Chapter Navigation Sidebar (desktop) */}
        {hasContent && (
          <ChapterNavigation
            unifiedStory={unifiedStory}
            repoStories={stories}
            activeChapterId={activeSection}
          />
        )}

        {/* Main Content */}
        <div className={`mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8 ${hasContent ? 'lg:ml-64 lg:max-w-4xl xl:ml-72' : ''}`}>
          {/* Back Button */}
          <Button
            variant="ghost"
            size="sm"
            onClick={() => router.push('/dashboard')}
            className="mb-6 -ml-2 text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Button>

          {/* Story Header */}
          <div ref={(el) => { registerSection('story-header', el); }}>
            <StoryHeader
              dateRangeStart={dateRange?.start}
              dateRangeEnd={dateRange?.end}
              progress={progress}
              isGenerating={isGenerating}
              error={error}
              onRegenerate={regenerate}
              totalRepos={selectedRepos.length}
              totalCommits={progress.totalCommits}
            />
          </div>

          {/* Generation Loading State — hide once streaming content is visible */}
          {isGenerating && !streamingDisplayStory && (
            <Card className="mb-8 border-purple-500/20 bg-gradient-to-br from-purple-950/20 to-background">
              <CardContent className="p-6">
                <div className="space-y-4">
                  <div className="flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-full bg-purple-500/10 text-purple-400">
                      {PHASE_ICONS[progress.phase] || <Loader2 className="h-5 w-5 animate-spin" />}
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <h3 className="text-sm font-semibold text-foreground">
                          {PHASE_LABELS[progress.phase] || 'Processing...'}
                        </h3>
                        <Badge variant="secondary" className="text-xs">
                          {Math.round(progress.overallProgress)}%
                        </Badge>
                      </div>
                      <p className="text-sm text-muted-foreground">{progress.currentStep}</p>
                    </div>
                  </div>

                  <Progress value={progress.overallProgress} className="h-2" />

                  <div className="flex flex-wrap items-center gap-4 text-xs text-muted-foreground">
                    {narrativeProgress.totalRepos > 0 && (
                      <span className="flex items-center gap-1">
                        <BookOpen className="h-3 w-3" />
                        {narrativeProgress.reposAnalyzed}/{narrativeProgress.totalRepos} repos analyzed
                      </span>
                    )}
                    {narrativeProgress.totalChapters > 0 && (
                      <span className="flex items-center gap-1">
                        <Sparkles className="h-3 w-3" />
                        {narrativeProgress.chaptersCompleted}/{narrativeProgress.totalChapters} chapters written
                      </span>
                    )}
                    {progress.totalCommits > 0 && (
                      <span className="flex items-center gap-1">
                        <GitCommit className="h-3 w-3" />
                        {progress.totalCommits.toLocaleString()} commits
                      </span>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Error State */}
          {error && !isGenerating && (
            <Card className="mb-8 border-destructive/30 bg-destructive/5">
              <CardContent className="p-6">
                <div className="flex items-start gap-3">
                  <AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-destructive" />
                  <div className="flex-1">
                    <h3 className="font-semibold text-destructive">Story Generation Failed</h3>
                    <p className="mt-1 text-sm text-muted-foreground">{error}</p>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={regenerate}
                      className="mt-3"
                    >
                      <RefreshCw className="mr-2 h-4 w-4" />
                      Try Again
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Content Area */}
          <div ref={contentRef} className="space-y-12">
            {/* Unified Developer Journey (or streaming preview) */}
            {effectiveStory && (
              <section
                id="unified-journey"
                ref={(el) => {
                  registerSection('unified-journey', el);
                  // Also use as the share capture target (more focused than full page)
                  (storyCaptureRef as React.MutableRefObject<HTMLElement | null>).current = el;
                }}
              >
                <UnifiedDeveloperJourney
                  story={effectiveStory}
                  onChapterVisible={(chapterId) => setActiveSection(chapterId)}
                />
                {/* Show streaming indicator when chapters are still arriving */}
                {isGenerating && streamingDisplayStory && (
                  <div className="mt-4 flex items-center gap-3 rounded-lg border border-purple-500/20 bg-purple-500/5 p-4">
                    <Loader2 className="h-4 w-4 animate-spin text-purple-400" />
                    <span className="text-sm text-muted-foreground">
                      {narrativeProgress.currentStep}
                    </span>
                  </div>
                )}
              </section>
            )}

            {/* Per-Repo Story Cards */}
            {stories.length > 0 && (
              <section
                id="repo-stories"
                ref={(el) => { registerSection('repo-stories', el); }}
              >
                <div className="mb-6 flex items-center gap-3">
                  <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-500/10">
                    <BookOpen className="h-4 w-4 text-blue-400" />
                  </div>
                  <h2 className="text-2xl font-bold tracking-tight">Repository Stories</h2>
                  <Badge variant="secondary" className="text-xs">
                    {stories.length} {stories.length === 1 ? 'repo' : 'repos'}
                  </Badge>
                </div>
                <PerRepoStoryCards
                  stories={stories}
                />
              </section>
            )}

            {/* Milestone Timeline */}
            {uniqueMilestones.length > 0 && (
              <section
                id="milestones"
                ref={(el) => { registerSection('milestones', el); }}
              >
                <div className="mb-6 flex items-center gap-3">
                  <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-500/10">
                    <Zap className="h-4 w-4 text-emerald-400" />
                  </div>
                  <h2 className="text-2xl font-bold tracking-tight">Key Milestones</h2>
                  <Badge variant="secondary" className="text-xs">
                    {uniqueMilestones.length} events
                  </Badge>
                </div>
                <MilestoneTimeline
                  milestones={uniqueMilestones}
                  repositories={selectedRepositories}
                />
              </section>
            )}

            {/* Share Section */}
            {hasContent && !isGenerating && (
              <section
                id="share"
                ref={(el) => { registerSection('share', el); }}
                className="pb-16"
              >
                <Card className="border-border/50 bg-gradient-to-br from-purple-950/10 via-background to-blue-950/10">
                  <CardContent className="flex flex-col items-center gap-4 p-8 text-center sm:flex-row sm:text-left">
                    <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-purple-500/20 to-blue-500/20">
                      <Share2 className="h-7 w-7 text-purple-400" />
                    </div>
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold">Share Your Developer Story</h3>
                      <p className="mt-1 text-sm text-muted-foreground">
                        Your journey across {selectedRepos.length} {selectedRepos.length === 1 ? 'repository' : 'repositories'} is worth sharing.
                        Download it, tweet it, or send the link to your team.
                      </p>
                    </div>
                    <Button
                      onClick={() => setShareOpen(true)}
                      className="shrink-0 bg-gradient-to-r from-purple-600 to-blue-600 text-white hover:from-purple-700 hover:to-blue-700"
                    >
                      <Share2 className="mr-2 h-4 w-4" />
                      Share Story
                    </Button>
                  </CardContent>
                </Card>
              </section>
            )}

            {/* Empty state when no content and not generating */}
            {!hasContent && !isGenerating && !error && (
              <Card className="border-dashed">
                <CardContent className="flex flex-col items-center justify-center p-16 text-center">
                  <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-purple-500/10">
                    <BookOpen className="h-8 w-8 text-purple-400" />
                  </div>
                  <h3 className="text-xl font-semibold">Your Story Awaits</h3>
                  <p className="mt-2 max-w-md text-sm text-muted-foreground">
                    Let Claude analyze your {selectedRepos.length} selected {selectedRepos.length === 1 ? 'repository' : 'repositories'} and craft a compelling narrative
                    about your developer journey — complete with chapters, milestones, and breakthroughs.
                  </p>
                  <Button
                    onClick={generateStory}
                    className="mt-6 bg-gradient-to-r from-purple-600 to-blue-600 text-white hover:from-purple-700 hover:to-blue-700"
                    size="lg"
                  >
                    <Sparkles className="mr-2 h-4 w-4" />
                    Generate My Story
                  </Button>
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      </div>

      {/* Share Dialog */}
      <ShareStory
        isOpen={shareOpen}
        onClose={() => setShareOpen(false)}
        title="Your Developer Story"
        shareText=""
        shareUrl=""
        captureRef={storyCaptureRef}
        repoCount={selectedRepos.length}
        commitCount={progress.totalCommits}
      />
    </div>
  );
}
